# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 03:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for this bot (can be different from twitter username)', max_length=64)),
                ('description', models.TextField(help_text='A brief description of how this bot looks on Twitter', null=True)),
                ('post_frequency', models.DurationField(choices=[(datetime.timedelta(0, 21600), 'Four times daily'), (datetime.timedelta(0, 43200), 'Twice daily'), (datetime.timedelta(1), 'Once Daily'), (datetime.timedelta(2), 'Every Other Day')], default='12 hours', help_text='how frequently this bot posts', null=True)),
                ('post_count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='when this bot was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='the last time this bot was updated')),
                ('consumer_key', models.CharField(help_text='consumer key from dev.twitter.com', max_length=255, null=True)),
                ('consumer_secret', models.CharField(help_text='consumer secret from dev.twitter.com ', max_length=255, null=True)),
                ('access_token', models.CharField(help_text='access token from dev.twitter.com', max_length=255, null=True)),
                ('access_token_secret', models.CharField(help_text='access token secret from dev.twitter.com', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
