# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20170113_1954'),
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='mashup',
            field=models.ManyToManyField(null=True, related_name='bots', to='content.Mashup'),
        ),
    ]
