# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_mashup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='mashup',
            field=models.ManyToManyField(related_name='bots', to='content.Mashup'),
        ),
    ]
