# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_auto_20170114_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='access_token',
            field=models.CharField(blank=True, help_text='access token from dev.twitter.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='access_token_secret',
            field=models.CharField(blank=True, help_text='access token secret from dev.twitter.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='consumer_key',
            field=models.CharField(blank=True, help_text='consumer key from dev.twitter.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='consumer_secret',
            field=models.CharField(blank=True, help_text='consumer secret from dev.twitter.com ', max_length=255, null=True),
        ),
    ]
