# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_auto_20170115_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterstatus',
            name='mashup',
        ),
    ]
