# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20170114_1526'),
        ('bots', '0009_auto_20170116_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='mashup',
            field=models.ForeignKey(default=1, help_text='the mashup used in creation', on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='content.Mashup'),
            preserve_default=False,
        ),
    ]
