# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_auto_20170123_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='post_count',
        ),
        migrations.AlterField(
            model_name='bot',
            name='post_frequency',
            field=models.DurationField(choices=[(datetime.timedelta(0, 21600), 'Four times daily'), (datetime.timedelta(0, 43200), 'Twice daily'), (datetime.timedelta(1), 'Once Daily'), (datetime.timedelta(2), 'Every Other Day')], default=datetime.timedelta(0, 43200), help_text='how frequently this bot posts', null=True),
        ),
    ]
