# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_auto_20170127_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='active',
            field=models.BooleanField(default=False, help_text='toggle switch examined when posting to twitter'),
        ),
    ]
