# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_bot_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='active',
            new_name='is_active',
        ),
    ]
