# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=32)),
                ('word2', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(help_text='The title for this source', max_length=64)),
                ('updated', models.DateTimeField()),
                ('description', models.TextField(help_text='A description of this source', null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('TW', 'Twitter'), ('EX', 'External')], max_length=2)),
                ('twitter_username', models.CharField(max_length=15, null=True)),
                ('author', models.TextField(max_length=64, null=True)),
                ('mash_count', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpora', to='people.Member')),
            ],
            options={
                'verbose_name_plural': 'corpora',
                'default_related_name': 'corpora',
            },
        ),
        migrations.CreateModel(
            name='Quadgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=32)),
                ('word2', models.CharField(max_length=32)),
                ('word3', models.CharField(max_length=32)),
                ('word4', models.CharField(max_length=32)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=1024)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Trigram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=32)),
                ('word2', models.CharField(max_length=32)),
                ('word3', models.CharField(max_length=32)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Corpus')),
            ],
        ),
        migrations.AddField(
            model_name='bigram',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Corpus'),
        ),
    ]
