# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=64)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.Corpus')),
            ],
        ),
    ]
