# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='corpora', to='people.Member'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='mash_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
