# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_corpus_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigram',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bigrams', to='sources.Corpus'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='sources.Corpus'),
        ),
        migrations.AlterField(
            model_name='quadgram',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadgrams', to='sources.Corpus'),
        ),
        migrations.AlterField(
            model_name='trigram',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigrams', to='sources.Corpus'),
        ),
        migrations.AlterField(
            model_name='word',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='sources.Corpus'),
        ),
    ]
