# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_auto_20161207_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='last_tweet_id',
            field=models.IntegerField(default=1, editable=False, help_text='id of most recent saved tweet'),
        ),
    ]
