# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_corpus_last_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='body',
            field=models.TextField(help_text='Body of external corpora', null=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='corpora', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='type',
            field=models.CharField(choices=[('TW', 'Twitter'), ('EX', 'Excerpt')], default='TW', max_length=2),
        ),
    ]
