# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0008_auto_20161222_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='last_tweet_id',
            field=models.BigIntegerField(default=1, editable=False, help_text='id of most recent saved tweet'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='mash_count',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
