# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_auto_20170105_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='twitter_username',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
