# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_auto_20170106_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='type',
        ),
        migrations.AddField(
            model_name='corpus',
            name='variety',
            field=models.CharField(choices=[('TW', 'Twitter User'), ('EX', 'Text Excerpt')], default='TW', max_length=2),
        ),
    ]
