# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_auto_20170106_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='twitter_hashtag',
            field=models.CharField(max_length=140, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='variety',
            field=models.CharField(choices=[('TW', 'Twitter User'), ('EX', 'Text Excerpt'), ('HS', 'Twitter Hashtag')], default='TW', max_length=2),
        ),
    ]
