# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_auto_20170123_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpora', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.TextField(),
        ),
    ]
