# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0014_auto_20170123_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='author',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
