# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mashup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MashupAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=144)),
                ('generated', models.DateTimeField(auto_now=True)),
                ('num_votes', models.PositiveIntegerField(default=0)),
                ('mashup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='content.Mashup')),
            ],
        ),
        migrations.AddField(
            model_name='mashup',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mashups', to='content.MashupAlgorithm'),
        ),
        migrations.AddField(
            model_name='mashup',
            name='corpora',
            field=models.ManyToManyField(related_name='corpora_set', to='sources.Corpus'),
        ),
    ]
