# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashup',
            name='description',
            field=models.TextField(default='An excellent and descriptive description'),
            preserve_default=False,
        ),
    ]
