# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20161205_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashup',
            name='algorithm',
            field=models.CharField(choices=[('MJN', 'Mouse Join')], default='MJN', max_length=3),
        ),
    ]
