# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20161205_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashup',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
