# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('content', '0006_mashup_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, help_text='when this bot was created')),
                ('name', models.CharField(help_text='A name for this bot (can be different from twitter username)', max_length=64)),
                ('post_frequency', models.DurationField(default='12 hours', help_text='how frequently this bot posts', null=True)),
                ('post_count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True, help_text='the last time this bot was updated')),
                ('consumer_key', models.CharField(help_text='consumer key from dev.twitter.com', max_length=255)),
                ('consumer_secret', models.CharField(help_text='consumer secret from dev.twitter.com ', max_length=255)),
                ('access_token', models.CharField(help_text='access token from dev.twitter.com', max_length=255)),
                ('access_token_secret', models.CharField(help_text='access token secret from dev.twitter.com', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='mashupalgorithm',
            old_name='usage_count',
            new_name='output_count',
        ),
        migrations.AddField(
            model_name='mashup',
            name='public',
            field=models.BooleanField(default=False, help_text='Whether to display this mashup and its output publicly'),
        ),
        migrations.AddField(
            model_name='bot',
            name='mashup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='content.Mashup'),
        ),
        migrations.AddField(
            model_name='bot',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='people.Member'),
        ),
    ]
