# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20161208_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashup',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
