# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0008_auto_20161209_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='member',
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mashup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mashups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mashup',
            name='algorithm',
            field=models.CharField(choices=[('MJN', 'Mouse Join'), ('BOW', 'Bag of Words'), ('MDB', 'Mad Lib')], default='MJN', max_length=3),
        ),
        migrations.AlterField(
            model_name='mashup',
            name='corpora',
            field=models.ManyToManyField(related_name='mashups', to='sources.Corpus'),
        ),
    ]
