# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_bot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='post_frequency',
            field=models.DurationField(choices=[('6 hours', 'Four times daily'), ('12 hours', 'Twice daily'), ('1 day', 'Once Daily'), ('2 days', 'Every Other Day')], default='12 hours', help_text='how frequently this bot posts', null=True),
        ),
    ]
