# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20161230_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='body',
            field=models.TextField(),
        ),
    ]
