# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0009_auto_20170105_1750'),
        ('content', '0012_auto_20170105_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='sentence',
            field=models.ManyToManyField(related_name='outputs', to='sources.Sentence'),
        ),
    ]
