# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_output_sentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='sentence',
            new_name='sentences',
        ),
    ]
