# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20170106_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='when this bot was created'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='post_frequency',
            field=models.DurationField(choices=[(datetime.timedelta(0, 21600), 'Four times daily'), (datetime.timedelta(0, 43200), 'Twice daily'), (datetime.timedelta(1), 'Once Daily'), (datetime.timedelta(2), 'Every Other Day')], default='12 hours', help_text='how frequently this bot posts', null=True),
        ),
        migrations.AlterField(
            model_name='mashup',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='generated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
