# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20170113_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='mashup',
        ),
        migrations.AddField(
            model_name='mashup',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='content.Bot'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='access_token',
            field=models.CharField(help_text='access token from dev.twitter.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='access_token_secret',
            field=models.CharField(help_text='access token secret from dev.twitter.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='consumer_key',
            field=models.CharField(help_text='consumer key from dev.twitter.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='consumer_secret',
            field=models.CharField(help_text='consumer secret from dev.twitter.com ', max_length=255, null=True),
        ),
    ]
