# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # Need to build bots first before using as ForeignKey field
        ('bots', '__first__'),
        ('content', '0016_auto_20170113_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='user',
        ),
        migrations.AlterField(
            model_name='mashup',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='bots.Bot'),
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
