# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20170113_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashup',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mashup', to='bots.Bot'),
        ),
    ]
