# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_mashup'),
        ('content', '0018_auto_20170113_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mashup',
            name='bot',
        ),
        migrations.AddField(
            model_name='mashup',
            name='bot',
            field=models.ManyToManyField(null=True, related_name='mashups', to='bots.Bot'),
        ),
    ]
