# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20170113_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashup',
            name='bot',
            field=models.ManyToManyField(related_name='mashups', to='bots.Bot'),
        ),
    ]
