# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0020_auto_20170114_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mashup',
            name='user',
        ),
        migrations.AddField(
            model_name='mashup',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mashups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
